const cards = [
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "523564",
        name: "Shahi Dastarkhwan",
        uuid: "2f1ea426-3cd1-4b1c-b780-cd7149e68e31",
        city: "3",
        area: "Banjara Hills",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "acwvb2nr6kriqnb5finh",
        cuisines: ["North Indian", "Chinese", "Kebabs", "Biryani", "Desserts"],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: "29 MINS",
        lastMileTravel: 5,
        slugs: {
          restaurant: "shahi-dastarkhwan-banjara-hills-banjara-hills",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "H No: 11-4-656/A, Lakdikapul, Hyderabad, Khairatabad Circle No.17 , Hyderabad  Central Zone, Telangana-500004",
        locality: "Lakdikapul",
        parentId: 180690,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 5200,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 5200,
          message: "",
          title: "Delivery Charge",
          amount: "5200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹299",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "523564",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "10062",
        name: "Kritunga Jagavi's Restaurant",
        uuid: "bc5f5720-c683-4994-bd08-9b6b869672e6",
        city: "3",
        area: "Somajiguda",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "ovjbah8onxfylfewnhdw",
        cuisines: [
          "Biryani",
          "Andhra",
          "Rayalaseema",
          "South Indian",
          "North Indian",
          "Chinese",
        ],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        slaString: "31 MINS",
        lastMileTravel: 5.900000095367432,
        slugs: {
          restaurant: "kritunga-restaurant-somajiguda-banjara-hills",
          city: "hyderabad",
        },
        cityState: "3",
        address: "Opposite Civil Supply Bhavan,Erramanzhil,Somjiguda,Hyderabad",
        locality: "Opposite Civil Supply Bhavan",
        parentId: 20088,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 5200,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 5200,
          message: "",
          title: "Delivery Charge",
          amount: "5200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7249729~p=19~eid=00000189-3ec1-6957-0e51-6ecf00521319~srvts=1688975010135",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "5.9 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "10062",
          deliveryTime: 31,
          minDeliveryTime: 31,
          maxDeliveryTime: 31,
          lastMileTravel: 5.900000095367432,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.9",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "1590",
        name: "Sarvi Restaurant",
        uuid: "c03d1018-4a31-44d3-8487-e1027ab088c8",
        city: "3",
        area: "Banjara Hills",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "ds6nasa6qpxunkhglz5g",
        cuisines: [
          "Biryani",
          "Chinese",
          "Indian",
          "Kebabs",
          "Tandoor",
          "Desserts",
        ],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 34,
        minDeliveryTime: 34,
        maxDeliveryTime: 34,
        slaString: "34 MINS",
        lastMileTravel: 6.900000095367432,
        slugs: {
          restaurant: "sarvi-banjara-hills",
          city: "hyderabad",
        },
        cityState: "3",
        address: "Opposite Care Hospital, Road 11, Banjara Hills",
        locality: "Road 11",
        parentId: 4623,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 6000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6000,
          message: "",
          title: "Delivery Charge",
          amount: "6000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 1,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.9 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "1590",
          deliveryTime: 34,
          minDeliveryTime: 34,
          maxDeliveryTime: 34,
          lastMileTravel: 6.900000095367432,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "IT_IS_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "2085",
        name: "Dadu's",
        uuid: "bd6b1377-2085-4fc4-a6c2-855291bf4188",
        city: "3",
        area: "Himayatnagar",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "709c05f458bdb729b684c65cb3a4654b",
        cuisines: ["Sweets", "Desserts", "Chaat", "Snacks", "Bakery"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        slaString: "28 MINS",
        lastMileTravel: 3.5999999046325684,
        slugs: {
          restaurant: "dadus-mithai-vatika-himayath-nagar",
          city: "hyderabad",
        },
        cityState: "3",
        address: "Opp. to TTD Temple, Liberty Road, 3-6-14",
        locality: "Liberty Road",
        parentId: 364048,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3700,
          message: "",
          title: "Delivery Charge",
          amount: "3700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7255376~p=22~eid=00000189-3ec1-6957-0e51-6ed00052165c~srvts=1688975010135",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "2085",
          deliveryTime: 28,
          minDeliveryTime: 28,
          maxDeliveryTime: 28,
          lastMileTravel: 3.5999999046325684,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.4",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "523794",
        name: "Capital Multicuisine Restaurant",
        uuid: "69beb71d-97b8-410b-bcf6-25193b8b0b92",
        city: "3",
        area: "Himayath Nagar",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "rkbt9oto4ub6d4uhmu35",
        cuisines: ["Biryani", "Arabian", "Lebanese"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 23,
        minDeliveryTime: 23,
        maxDeliveryTime: 23,
        slaString: "23 MINS",
        lastMileTravel: 2.0999999046325684,
        slugs: {
          restaurant:
            "capital-multicuisine-restaurant-himayath-nagar-himayath-nagar",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "CAPITAL MULTI CUISINE RESTAURANT 3-6-285/A , Hyderguda Street No.4 , Opposite OLD MLA Quarters, Hyderguda - Basheerbagh Road, Hyderabad, Telangana-500029",
        locality: "Himayath Nagar",
        parentId: 19262,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2600,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2600,
          message: "",
          title: "Delivery Charge",
          amount: "2600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "523794",
          deliveryTime: 23,
          minDeliveryTime: 23,
          maxDeliveryTime: 23,
          lastMileTravel: 2.0999999046325684,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.6",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "371351",
        name: "Andhra Meals",
        uuid: "7fbfd8e7-02fa-4e3b-9c94-f5f53e17f38e",
        city: "3",
        area: "Mehdipatnam",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "hjpbgpuoarzjiyarrqy5",
        cuisines: ["South Indian"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: "29 MINS",
        lastMileTravel: 6.5,
        slugs: {
          restaurant: "andhra-meals-mehdipatnam-mehdipatnam",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "beside swathi Hotel, Near bus stop, Mehdipatnam, Hyderabad -500028",
        locality: "",
        parentId: 33189,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 6000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6000,
          message: "",
          title: "Delivery Charge",
          amount: "6000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "371351",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 6.5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "28108",
        name: "Al Rabea Al Arabi Cafeteria",
        uuid: "10573e6b-6833-4990-9412-d6397ae3f3ec",
        city: "3",
        area: "Mehdipatnam",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "jnzmscxd37rbjmgciwt5",
        cuisines: ["Arabian", "Lebanese"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        slaString: "30 MINS",
        lastMileTravel: 7.599999904632568,
        slugs: {
          restaurant: "alrabea-al-arabi-cafeteria-mehdipatnam-mehdipatnam",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "Shop Number 12-2-772,Pillar Number 37, Dilshad Nagar Colony Rd, Rethi Bowli, P & T Colony, Mehdipatnam, Hyderabad",
        locality: "Pillar no 37",
        parentId: 7582,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 6800,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6800,
          message: "",
          title: "Delivery Charge",
          amount: "6800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 1,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "28108",
          deliveryTime: 30,
          minDeliveryTime: 30,
          maxDeliveryTime: 30,
          lastMileTravel: 7.599999904632568,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "IT_IS_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "495772",
        name: "Cafe Niloufer",
        uuid: "9a064df4-fa62-4048-a4af-bf626c82dfee",
        city: "3",
        area: "Himayath Nagar",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "e0c63e989612732c70da6d1bb6984850",
        cuisines: ["Bakery", "Beverages", "Snacks", "Desserts"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        slaString: "24 MINS",
        lastMileTravel: 1.7999999523162842,
        slugs: {
          restaurant: "café-niloufer-himayath-nagar-himayath-nagar",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "M/S. ABR CAFE AND BAKERS PRIVATE LIMITED, 3-5-900, Old MLA Quarters Road, HimayathNagar, Hyderabad-Central Zone, Telangana-500029.",
        locality: "Old Mla Quarters Road",
        parentId: 9152,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2600,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2600,
          message: "",
          title: "Delivery Charge",
          amount: "2600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7255428~p=28~eid=00000189-3ec1-6957-0e51-6ed200521c15~srvts=1688975010135",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.7 kms",
        hasSurge: false,
        sla: {
          restaurantId: "495772",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          lastMileTravel: 1.7999999523162842,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.5",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "104383",
        name: "Sri Abhiruchi Biryani & Chinese Fast Food",
        uuid: "80abf833-08a2-46f7-be6a-642ffbc7e843",
        city: "3",
        area: "Dilsukhnagar",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "demt2lduddamfjtcjz4s",
        cuisines: ["Biryani"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 22,
        minDeliveryTime: 22,
        maxDeliveryTime: 22,
        slaString: "22 MINS",
        lastMileTravel: 4.599999904632568,
        slugs: {
          restaurant:
            "sri-abhiruchi-biryani-chinese-fast-food-dilsukhnagar-kothapet-dilsukhnagar",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "C.S-1, plot no:27/A,H.No:16-11-477/6/5/1,sai towers,moosarambagh,Dilsukhnagar,500060",
        locality: "moosarambagh",
        parentId: 193305,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3700,
          message: "",
          title: "Delivery Charge",
          amount: "3700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 1,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "10% OFF",
          subHeader: "ABOVE ₹600",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "104383",
          deliveryTime: 22,
          minDeliveryTime: 22,
          maxDeliveryTime: 22,
          lastMileTravel: 4.599999904632568,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "IT_IS_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "417281",
        name: "Shree Santosh Family Dhaba",
        uuid: "cbef0e4e-1d73-4570-9783-e11cd8a8558f",
        city: "3",
        area: "Kothapet & Dilsukhnagar",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "lhhwuzpjnufjn3sjhr8k",
        cuisines: ["North Indian", "Biryani", "Chinese", "Indian", "Tandoor"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        slaString: "30 MINS",
        lastMileTravel: 6.400000095367432,
        slugs: {
          restaurant:
            "shree-santosh-family-dhaba-kothapet-&-dilsukhnagar-kothapet-&-dilsukhnagar",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "13-18-96, Near Bhagya Shree Function Hall, Chaitanyapuri, Opp Bus Stop Dilsukhnagar",
        locality: "Chaitanyapuri",
        parentId: 3003,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 6000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6000,
          message: "",
          title: "Delivery Charge",
          amount: "6000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7255432~p=31~eid=00000189-3ec1-6957-0e51-6ed300521f68~srvts=1688975010135",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.4 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "417281",
          deliveryTime: 30,
          minDeliveryTime: 30,
          maxDeliveryTime: 30,
          lastMileTravel: 6.400000095367432,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.9",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "3324",
        name: "Srikanya",
        uuid: "63fec48e-9858-4593-a8ce-a5248570d59b",
        city: "3",
        area: "Punjagutta",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "tw4ytwle8yommmgdy4b0",
        cuisines: ["Andhra", "Seafood"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        slaString: "32 MINS",
        lastMileTravel: 6.900000095367432,
        slugs: {
          restaurant: "sri-kanya-banjara-hills",
          city: "hyderabad",
        },
        cityState: "3",
        address: "Behind Model House,Bylane of NIMS, Punjagutta,Hyderabad",
        locality: "Punjagutta Road",
        parentId: 7317,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 6000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6000,
          message: "",
          title: "Delivery Charge",
          amount: "6000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 1,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.9 kms",
        hasSurge: false,
        sla: {
          restaurantId: "3324",
          deliveryTime: 32,
          minDeliveryTime: 32,
          maxDeliveryTime: 32,
          lastMileTravel: 6.900000095367432,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "IT_IS_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "140117",
        name: "Imperial Multi Cuisine Restaurant",
        uuid: "2fc26248-e811-4af0-8f7c-891d19f85440",
        city: "3",
        area: "Malakpet",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "ib97mlmkhuwwv51syyca",
        cuisines: ["Biryani", "Chinese", "Indian", "Kebabs", "Tandoor"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 21,
        minDeliveryTime: 21,
        maxDeliveryTime: 21,
        slaString: "21 MINS",
        lastMileTravel: 3.5999999046325684,
        slugs: {
          restaurant:
            "imperial-multi-cuisine-restaurant-saroor-nagar-kothapet-dilsukhnagar",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "opp petrol pump, saidabad x road, hyderabad, telengana, 500059",
        locality: "saidabad x road",
        parentId: 19253,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3700,
          message: "",
          title: "Delivery Charge",
          amount: "3700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "30% OFF",
          subHeader: "UPTO ₹75",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "140117",
          deliveryTime: 21,
          minDeliveryTime: 21,
          maxDeliveryTime: 21,
          lastMileTravel: 3.5999999046325684,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "179095",
        name: "Subbayya Gari Hotel",
        uuid: "9ca5dc71-125a-4ddb-998b-ff845e55039a",
        city: "3",
        area: "Old Malakpet",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "wnln2kbetcoxacsj8kao",
        cuisines: ["South Indian", "Andhra", "Sweets"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 22,
        minDeliveryTime: 22,
        maxDeliveryTime: 22,
        slaString: "22 MINS",
        lastMileTravel: 4.300000190734863,
        slugs: {
          restaurant:
            "subbayya-gari-hotel-sri-krupa-market-malakpet-kothapet-dilsukhnagar",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "Shop no 47 Mahboob Mansion, Sri Krupa Market, Malakpet, Hyderabad, Telangana 500036",
        locality: "Sri Krupa Market, Malakpet",
        parentId: 12343,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3700,
          message: "",
          title: "Delivery Charge",
          amount: "3700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "10% OFF",
          subHeader: "UPTO ₹40",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "179095",
          deliveryTime: 22,
          minDeliveryTime: 22,
          maxDeliveryTime: 22,
          lastMileTravel: 4.300000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "88440",
        name: "Hotel Shadab",
        uuid: "61340fdb-cf65-4960-9555-1ac5b2222450",
        city: "3",
        area: "Ghansi Bazaar",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "7f6e244e5612ab41e3f72679e697843a",
        cuisines: ["Biryani", "North Indian", "Chinese"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 45,
        minDeliveryTime: 45,
        maxDeliveryTime: 45,
        slaString: "45 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "shadab-ghansi-bazaar-charminar",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "Plot 21, Opposite Madina Building, High Court Road, Ghansi Bazaar, Hyderabad\t\t\t\t\t",
        locality: "High Court Road",
        parentId: 19124,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3700,
          message: "",
          title: "Delivery Charge",
          amount: "3700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹299",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "88440",
          deliveryTime: 45,
          minDeliveryTime: 45,
          maxDeliveryTime: 45,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "4614",
        name: "Crystal Restaurant",
        uuid: "92fe33e8-57e2-40a7-a503-d10b5426a4d2",
        city: "3",
        area: "Himayatnagar",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "uptjd3ljpsjszvkjcok7",
        cuisines: ["Biryani", "North Indian", "Chinese"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 22,
        minDeliveryTime: 22,
        maxDeliveryTime: 22,
        slaString: "22 MINS",
        lastMileTravel: 3.5,
        slugs: {
          restaurant: "crystal-restaurant-nallakunta",
          city: "hyderabad",
        },
        cityState: "3",
        address: "1-1-169/1,2,3, Crystal Building, RTC X roads, Hyd - 20",
        locality: "RTC X roads",
        parentId: 1880,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3700,
          message: "",
          title: "Delivery Charge",
          amount: "3700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "4614",
          deliveryTime: 22,
          minDeliveryTime: 22,
          maxDeliveryTime: 22,
          lastMileTravel: 3.5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "115662",
        name: "Amfah Hotel",
        uuid: "b22de964-f028-434e-86f0-5f897315a5e6",
        city: "3",
        area: "Mehdipatnam",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "ppw2cr9w2yye6umriuwi",
        cuisines: ["Biryani", "North Indian", "Chinese"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: "29 MINS",
        lastMileTravel: 6.5,
        slugs: {
          restaurant: "amfah-hotel-mehdipatnam-mehdipatnam",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "Near Rytu Bazar Bus Stop, Mehdipatnam, Vivekananda Colony, Santosh Nagar, Mehdipatnam, Hyderabad, Telangana 500008",
        locality: "Near Rytu Bazar Bus Stop",
        parentId: 31520,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 6000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6000,
          message: "",
          title: "Delivery Charge",
          amount: "6000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "115662",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 6.5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.6",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
];

export default cards;
